"use client";

import React, { useState } from "react";
import { Plus, Minus } from "lucide-react";

interface FaqItem {
  id: string;
  question: string;
  answer: string;
  category: string;
}

const faqData: FaqItem[] = [
  {
    id: "faq-1",
    category: "Verification & Geofencing",
    question: "How does the system verify my physical presence in the laboratory?",
    answer:
      "UA LabSign cross-references your device's real-time GPS coordinates against the pre-configured 65-meter laboratory perimeter at the exact second you submit the 4-digit room PIN generated by your instructor.",
  },
  {
    id: "faq-2",
    category: "Anti-Proxy Security",
    question: "Can I submit laboratory attendance for a classmate using my device?",
    answer:
      "No. UA LabSign enforces a strict single-device binding policy using ECDSA P-256 asymmetric cryptography. Your account is bound to your specific device, preventing proxy check-ins or account sharing.",
  },
  {
    id: "faq-3",
    category: "Privacy & Telemetry",
    question: "Is my location tracked continuously in the background during class hours?",
    answer:
      "No. Location telemetry is evaluated strictly during the single moment of session PIN submission. UA LabSign never enables continuous background location tracking, preserving your location privacy outside check-in moments.",
  },
  {
    id: "faq-4",
    category: "Device Migration & Account Access",
    question: "What should I do if I change, upgrade, or replace my mobile device?",
    answer:
      "You can transfer your account self-service. Log in on your new device using your official university Google account (@ua.edu.ph) and enter your 6-digit Recovery PIN created during onboarding. This automatically revokes and unbinds your old hardware.",
  },
  {
    id: "faq-5",
    category: "Authentication & Eligibility",
    question: "Which email accounts are eligible to access the UA LabSign system?",
    answer:
      "Access is restricted exclusively to active University of Assumption institutional Google accounts ending in @ua.edu.ph. Personal Gmail accounts or external emails are automatically rejected at the login portal.",
  },
  {
    id: "faq-6",
    category: "Session PINs & Expiry",
    question: "Why does my check-in attempt say 'Session Expired' or 'Invalid PIN'?",
    answer:
      "Instructors activate session PINs with a strict active duration ranging from 1 to 15 minutes. Submissions attempted outside this active window or after the session timer expires will be rejected to prevent delayed check-ins.",
  },
];

export default function FaqSection() {
  const [openId, setOpenId] = useState<string | null>("faq-1");

  const toggleFaq = (id: string) => {
    setOpenId(openId === id ? null : id);
  };

  return (
    <section
      id="faq"
      className="bg-white text-[#011B51] py-20 md:py-28 border-b border-gray-200/80"
    >
      <div className="max-w-7xl mx-auto px-6">
        <div className="grid lg:grid-cols-12 gap-12 lg:gap-16 items-start text-left">
          
          {/* Left Column: Section Header */}
          <div className="lg:col-span-5 lg:sticky lg:top-28 space-y-4">
            <span className="text-xs font-black text-[#A51A21] uppercase tracking-widest block border-l-2 border-[#A51A21] pl-3">
              Questions &amp; Support
            </span>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#011B51] tracking-tight leading-snug">
              Frequently Asked Questions
            </h2>
            <p className="text-sm sm:text-base font-semibold text-gray-600 leading-relaxed">
              Find clear answers regarding geofence verification, device binding, cryptographic privacy, and attendance policies across University of Assumption laboratories.
            </p>
          </div>

          {/* Right Column: Interactive Accordion List */}
          <div className="lg:col-span-7 divide-y divide-gray-200 border-t border-b border-gray-200">
            {faqData.map((item) => {
              const isOpen = openId === item.id;
              return (
                <div key={item.id} className="py-6 transition-colors">
                  <button
                    onClick={() => toggleFaq(item.id)}
                    className="w-full flex items-start justify-between text-left group focus:outline-none cursor-pointer"
                    aria-expanded={isOpen}
                  >
                    <div className="pr-6 space-y-1">
                      <span className="text-[10px] font-extrabold text-[#A51A21] uppercase tracking-widest block">
                        {item.category}
                      </span>
                      <h3 className="text-base sm:text-lg font-extrabold text-[#011B51] group-hover:text-[#A51A21] transition-colors leading-snug">
                        {item.question}
                      </h3>
                    </div>

                    <div className="mt-1 w-7 h-7 rounded-lg border border-gray-200 flex items-center justify-center shrink-0 group-hover:border-[#011B51] transition-colors">
                      {isOpen ? (
                        <Minus className="w-4 h-4 text-[#A51A21]" />
                      ) : (
                        <Plus className="w-4 h-4 text-[#011B51]" />
                      )}
                    </div>
                  </button>

                  {/* Expandable Answer Area */}
                  {isOpen && (
                    <div className="pt-3 pr-8">
                      <p className="text-xs sm:text-sm text-gray-600 font-medium leading-relaxed">
                        {item.answer}
                      </p>
                    </div>
                  )}
                </div>
              );
            })}
          </div>

        </div>
      </div>
    </section>
  );
}