// app/api/student/attendance/route.ts

import { NextResponse } from "next/server";
import crypto from "crypto";
import { db } from "@/lib/db";

/**
 * Verifies an ECDSA signature generated by the client using the public key stored in PEM format.
 */
async function verifyEcdsaSignature(
  message: string,
  signatureBase64: string,
  publicKeyPem: string
): Promise<boolean> {
  try {
    const verify = crypto.createVerify("SHA256");
    verify.update(message);
    verify.end();

    const signatureBuffer = Buffer.from(signatureBase64, "base64");

    return verify.verify(
      {
        key: publicKeyPem,
        format: "pem",
        type: "spki",
      },
      signatureBuffer
    );
  } catch (error) {
    console.error("ECDSA Signature Verification Exception:", error);
    return false;
  }
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { studentId, labRoom, timestamp, signature, roomPin } = body;

    // 1. Validate required payload parameters
    if (!studentId || !labRoom || !timestamp || !signature || !roomPin) {
      return NextResponse.json(
        { success: false, message: "Missing required attendance parameters." },
        { status: 400 }
      );
    }

    // 2. Query Student Record & Public Key
    const student = await db.student.findUnique({
      where: { student_id: studentId },
    });

    if (!student || !student.public_key) {
      return NextResponse.json(
        { 
          success: false, 
          message: "DEVICE_REVOKED: This device is not registered or authorization was revoked." 
        },
        { status: 403 }
      );
    }

    // 3. Query Active Lab Session
    const activeSession = await db.session.findFirst({
      where: {
        lab_room: labRoom,
        is_active: true,
      },
    });

    if (!activeSession) {
      return NextResponse.json(
        { success: false, message: `No active class session currently open for ${labRoom}.` },
        { status: 404 }
      );
    }

    // 4. Validate Room PIN
    if (activeSession.pin !== roomPin) {
      return NextResponse.json(
        { success: false, message: "Incorrect room PIN. Please check the PIN displayed on the board." },
        { status: 400 }
      );
    }

    // 5. Check duplicate check-ins
    const existingLog = await db.attendanceLog.findFirst({
      where: {
        student_id: studentId,
        session_id: activeSession.id,
      },
    });

    if (existingLog) {
      return NextResponse.json(
        { success: false, message: "You have already logged attendance for this session." },
        { status: 409 }
      );
    }

    // 6. Cryptographic Signature Verification
    const isSignatureValid = await verifyEcdsaSignature(
      `${studentId}-${labRoom}-${timestamp}`,
      signature,
      student.public_key
    );

    if (!isSignatureValid) {
      return NextResponse.json(
        { success: false, message: "Security verification failed. Digital signature invalid." },
        { status: 401 }
      );
    }

    // 7. Log Attendance Record in DB
    await db.attendanceLog.create({
      data: {
        student_id: studentId,
        session_id: activeSession.id,
        timestamp: new Date(timestamp),
      },
    });

    return NextResponse.json({
      success: true,
      message: `Attendance verified and recorded for ${labRoom}!`,
    });

  } catch (error: any) {
    console.error("Attendance API Error:", error);
    return NextResponse.json(
      { success: false, message: "Server error processing request. Please try again." },
      { status: 500 }
    );
  }
}